// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMzCzKeaIDQm0lPk_rXO3TRIq04JHIvkc',
    appId: '1:310785614071:web:83884a620f64f84817f3f2',
    messagingSenderId: '310785614071',
    projectId: 'my-recipe-app-5bb30',
    authDomain: 'my-recipe-app-5bb30.firebaseapp.com',
    storageBucket: 'my-recipe-app-5bb30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChoIsChlNlrUBj03l3oQTNLCd9LLTKTEo',
    appId: '1:310785614071:android:64b2c39c88476b3617f3f2',
    messagingSenderId: '310785614071',
    projectId: 'my-recipe-app-5bb30',
    storageBucket: 'my-recipe-app-5bb30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7VM-shHSEO9i279rGZpJFz8XO5YdrgEI',
    appId: '1:310785614071:ios:28b5ecb8d2fa8e7717f3f2',
    messagingSenderId: '310785614071',
    projectId: 'my-recipe-app-5bb30',
    storageBucket: 'my-recipe-app-5bb30.firebasestorage.app',
    iosClientId: '310785614071-m6a0emn6q7v60qeoluje81iv6iqb3kcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7VM-shHSEO9i279rGZpJFz8XO5YdrgEI',
    appId: '1:310785614071:ios:28b5ecb8d2fa8e7717f3f2',
    messagingSenderId: '310785614071',
    projectId: 'my-recipe-app-5bb30',
    storageBucket: 'my-recipe-app-5bb30.firebasestorage.app',
    iosClientId: '310785614071-m6a0emn6q7v60qeoluje81iv6iqb3kcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibRecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMzCzKeaIDQm0lPk_rXO3TRIq04JHIvkc',
    appId: '1:310785614071:web:93cf59d8eaf5806417f3f2',
    messagingSenderId: '310785614071',
    projectId: 'my-recipe-app-5bb30',
    authDomain: 'my-recipe-app-5bb30.firebaseapp.com',
    storageBucket: 'my-recipe-app-5bb30.firebasestorage.app',
  );
}
